99 show pen beside every volunteerdetailcontact
volo-db/volodb-frontend pull request #159
Opened 2024-07-09 14:18 UTC by jessica-schubert

2024-07-09 14:51 UTC, Artromi commented
when the edit formular is open, the input field and label should show the already existing data

2024-07-09 14:52 UTC, Artromi requested changes
when the edit formular is open, the input field and label should show the already existing data

2024-07-10 05:31 UTC, Artromi requested changes
when the edit formular is open, the input field and label should show the already existing data

2024-07-11 13:14 UTC, fabian-urner approved these changes

2024-07-11 15:22 UTC, Artromi approved these changes

2024-07-11 15:29 UTC, Artromi approved these changes

2024-07-11 15:29 UTC, merged