71 projectformular add datafields and page 2
volo-db/volodb-frontend pull request #72
Opened 2024-06-05 11:27 UTC by Artromi

2024-06-05 12:10 UTC, fabian-urner requested changes
1. While using the formular it is a little bit confusing to be able to submit the form while beeing on the first page. Maybe it's better to disable the submit button until u reached the last page and validate the input-fields by clicking the next/back buttons

2. The zip-code input-field should be type="text" so the browser can give u hints by typing and there are a lot of countrys with dashes or slashes in the zipcode

3.  after submitting the form, the dialog stays "open". So clicked a few times and submitted a lot of the same projects 😄

2024-06-06 05:03 UTC, fabian-urner requested changes
1. Something is not working with the Email and PhoneNr-Validation. It accepts wrong input anyway...

2. If there is a Error with the backend wen run into a infinite loop (also after closing the dialog):
![Bildschirmfoto 2024-06-06 um 06 52 49](https://github.com/volo-db/volodb-frontend/assets/144705156/ebe6aeea-dca6-42a2-a13a-f2577d8664c9)

-> It would be better if the form is shown again with emty fields or better: with the prefilled fields wich are valid and red shaking fields where the error occurred

3. Because of the country-input-field is of type="text" there will be a lot of Backend-Errors if there is a typo... I quickly wrote a route to get all countrys (/api/v1/countrys) -> maybe it's better to have a listbox with all countrys and "Deutschland" is preselected
(⚠️ you have to choose localName in the json-objects wich cames from the backend. If localName is null -> ignore the country)

2024-06-07 11:01 UTC, Artromi commented
> 1. Something is not working with the Email and PhoneNr-Validation. It accepts wrong input anyway...
> 2. If there is a Error with the backend wen run into a infinite loop (also after closing the dialog):
>    ![Bildschirmfoto 2024-06-06 um 06 53 08](https://private-user-images.githubusercontent.com/144705156/337124230-d8a6f933-8a97-4e86-81f3-8e9a1d812b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTY1MzEsIm5iZiI6MTcxNzc1NjIzMSwicGF0aCI6Ii8xNDQ3MDUxNTYvMzM3MTI0MjMwLWQ4YTZmOTMzLThhOTctNGU4Ni04MWYzLThlOWExZDgxMmIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMDMwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTNmMjY5MDQ5MWVkNGYxNmZlYWYwN2ZjNWU4MDhmZGFkNTRjYTA1NTY4ZjZlMzA2NGJlYmQwYWFkZmIzNzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UfawqitjSCWwgfNPG64YwMBIDCbjiWGxU_IrXy4Lg3k)
> 
> -> It would be better if the form is shown again with emty fields or better: with the prefilled fields wich are valid and red shaking fields where the error occurred
> 
> 3. Because of the country-input-field is of type="text" there will be a lot of Backend-Errors if there is a typo... I quickly wrote a route to get all countrys (/api/v1/countrys) -> maybe it's better to have a listbox with all countrys and "Deutschland" is preselected
>    (⚠️ you have to choose localName in the json-objects wich cames from the backend. If localName is null -> ignore the country)

-> everything should(!) be woring now :D 
-> also: i made an message on page 2 of the formular in case of validation errors on page 2 because i thought its confusing 
     without any indication why nothing got submitted when on page 2 everything is fine
-> easterEgg:  find the  🤠

2024-06-10 05:57 UTC, fabian-urner commented on src/stores/CountryStore.js
> +//  ### 🤠 ###
found it! 🐣

2024-06-10 06:03 UTC, Artromi commented on src/stores/CountryStore.js
> +//  ### 🤠 ###
💐

2024-06-10 06:34 UTC, fabian-urner requested changes
Everything is working like expected! 🎉

## Just two tiny 🪲's:
1. There is no need in the CountryStore 🤠 to make an Array out of Countrys because you already have on from the backend. Further the array-method never clear the array so on reload you have every country in the ListBox twice and so on...
 
![Bildschirmfoto 2024-06-10 um 07 55 26](https://github.com/volo-db/volodb-frontend/assets/144705156/b4f20c85-25b1-4214-b9ee-3308ffa8dee9)

2. wrong overflow on page 2:
![Bildschirmfoto 2024-06-10 um 07 51 52](https://github.com/volo-db/volodb-frontend/assets/144705156/455ee620-0f5a-417c-b7f3-52646de233d1)



> ### In general:
> As you say: It's confusing to get errors on the second page for errors on the 1st page. When I go back to the 1st page to fix the error, it's confusing to not be able to submit the form just by the fact that I'm on page 1....
The more we deal with this formular-(validation), the more I find it necessary to use a validation-lib for it...
So in conclusion: I'm not very happy with the form as it is. But I think we have to go further 😄

2024-06-10 06:34 UTC, fabian-urner commented on src/stores/CountryStore.js
> +      countrysPage: null,
there is no Pagination build in for countries. So you can just call it countries. (suddenly I realize that it should be “countries” and not “countrys” 🙈) I change the route on the backend as well...

2024-06-10 06:34 UTC, fabian-urner commented on src/stores/CountryStore.js
> +        this.createCountrysArray()
you don't need createCountrysArray... becaus you already got it from the backend (-> no pagination)

2024-06-10 06:34 UTC, fabian-urner commented on src/stores/CountryStore.js
> +        this.fetching = false
fetching never set to "true"

2024-06-10 06:34 UTC, fabian-urner commented on src/components/ProjectFormular.vue
> +          this.projectStore.fetching = false
this could not be right. If there is a timeout problem we have to handle it directly in the store or check the backend for errors.

2024-06-10 06:34 UTC, fabian-urner commented on src/components/VolunteerFormular.vue
> +         this.volunteerStoreStore.fetching = false
this could not be right. If there is a timeout problem we have to handle it directly in the store or check the backend for errors.

2024-06-11 09:11 UTC, fabian-urner approved these changes

2024-06-11 09:11 UTC, merged