21 navbarbutton component with button type property
volo-db/volodb-frontend pull request #80
Opened 2024-06-12 11:03 UTC by jessica-schubert

2024-06-13 07:36 UTC, fabian-urner requested changes
need to implement the whole issue

2024-06-18 13:45 UTC, Artromi commented on src/App.vue
> +    <NavigationBar> </NavigationBar>
just use "<NavigationBar />" instead of "<NavigationBar> </NavigationBar" if there is nothing to add inside

2024-06-20 08:21 UTC, fabian-urner approved these changes

2024-06-20 08:22 UTC, Artromi approved these changes

2024-06-20 08:22 UTC, merged